const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const parts = [
  "src/layout/start.html",
  "src/components/01-accents.html",
  "src/components/02-colors.html",
  "src/components/03-typography.html",
  "src/components/04-buttons.html",
  "src/components/05-forms.html",
  "src/components/06-labels.html",
  "src/components/07-alerts.html",
  "src/components/08-tables.html",
  "src/components/09-tabs.html",
  "src/components/10-cards.html",
  "src/components/11-accordion.html",
  "src/components/12-nav.html",
  "src/components/13-icons.html",
  "src/components/14-progress.html",
  "src/components/15-lists.html",
  "src/components/16-headings.html",
  "src/components/17-tiles.html",
  "src/components/18-overlay.html",
  "src/components/19-dotnav.html",
  "src/components/20-text-utils.html",
  "src/components/21-utility.html",
  "src/components/22-masthead.html",
  "src/components/23-breadcrumb.html",
  "src/components/24-inputfields.html",
  "src/components/25-module-guidelines.html",
  "src/components/26-modals.html",
  "src/components/27-offcanvas.html",
  "src/components/28-notifications.html",
  "src/components/29-pagination.html",
  "src/components/30-description-list.html",
  "src/components/31-dropdown.html",
  "src/components/32-lightbox.html",
  "src/components/33-search.html",
  "src/components/34-comment.html",
  "src/components/35-panel.html",
  "src/components/36-overrides.html",
  "src/layout/end.html",
];

const banner = "<!-- Generated by scripts/build.js. Edit src/components, src/layout, assets/css, or assets/js. -->\n";
const html = banner + parts.map((file) => fs.readFileSync(path.join(root, file), "utf8").trimEnd()).join("\n\n") + "\n";

for (const output of ["index.html", "Draft-AdminThemeUikit-DesignSystem-UIKit.html"]) {
  fs.writeFileSync(path.join(root, output), html);
}

console.log("Built index.html and Draft-AdminThemeUikit-DesignSystem-UIKit.html from " + parts.length + " parts.");
